#!/bin/sh

set -e

# http://www.ipinfodb.com/ip_location_api.php
# query form: http://www.ipinfodb.com/

API="http://api.ipinfodb.com/v3/ip-city?key="
APIKEY="eb6f1e5a602904aa9e870d8f31c96b993ac381852b186e887ef98cb5c0ffc6bc"
XMLGET=curl
XML=xmlstarlet

usage () { echo "usage: `basename $0` [ -v ] " ; return 0 ; }
usageerr () { usage >&2 ; return 1 ; }

if [ "$1" = "-v" ] ; then
	VERBOSE=1
elif [ $# -gt 0 ] ; then
	usageerr
fi

"$XMLGET" "$API$APIKEY&format=xml" | "$XML" sel -t -c //timeZone
