#!/bin/sh

set -e


usage () { echo "usage: `basename $0` --tz | --cc | --help" ; return 0 ; }
usageerr () { usage >&2 ; return 1 ; }

USETZ=0
USECC=0

export HOROBIN="`dirname $0`/"

gettz () {
	"$HOROBIN"ipinfodb 2> /dev/null
}

getcc () {
	echo "Not yet implemented, sorry" >&2
	# just get -t -c //countryCode from ipinfodb
	return 1
}

set -- $(getopt -l cc,help,tz "" "$@")
while [ $# -gt 0 ] ; do
	case "$1" in
		--tz)
			USETZ=1
			;;
		--cc)
			USECC=1
			;;
		--help)
			usage
			exit 0
			;;
		--)
			break
			;;
		*)
			usageerr
			;;
	esac
	shift
done
if [ $USETZ -eq 0 -a $USECC -eq 0 ] ; then
	usageerr
fi
if [ $USETZ -ne 0 ] ; then
	gettz
fi
if [ $USECC -ne 0 ] ; then
	getcc
fi
